version: '3.8'
services:
    postgres:
        image: postgres
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
    webserver:
        image: dylanray93/dylan_airflow_image
        entrypoint: ./scripts/entrypoint.sh
        deploy:
            restart_policy:
                condition: any
        depends_on:
            - postgres
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./scripts:/opt/airflow/scripts
            - ./data:/data
        ports:
            - "8080:8080"
    scheduler:
        image: dylanray93/dylan_airflow_image
        command: scheduler
        deploy:
            restart_policy:
                condition: any
        depends_on:
            - postgres
            - webserver
        env_file:
            - .env
        volumes:
            - ./dags:/opt/airflow/dags
            - ./logs:/opt/airflow/logs
            - ./data:/data
